### PR TITLE
Inspector test

### PR DESCRIPTION
**Pull request by Dilvish-fo**
5d303594 shows the update I generated first; it seems to have a great many differences resulting purely from platform differences, being for Linux versus the previous was for windows.  It would probably be worthwhile to make it ignore these differences rather than update the stub for them.

I then updated with Morlic's commit having a small number of interface changes regarding starlaneSpeed->speed.  The stub changes are in e35ffe78.  It picked up the change to the Hulltype class fine; for the enum changes it missed that the new name supplemented/duplicated an old name rather than superseding it. That's not terrible-- we are unlikely to plan on having duplicate enums indefinitely, and this might facilitate flagging where the scripts needs to be updated for when the transition duplication ends.

### CODE REVIEW

**Comment by Cjkjvfnby** [comment]
I update my branch to ignore platform dependencies. Can you commit your result again?

I did nothing about duplicated enum names. IMHO this transition can be done only via python by updating `extend_free_orion_AI_interface`

**Comment by Cjkjvfnby** [comment]
Hello.

**Comment by Dilvish-fo** [comment]
yes, hi, I'll see if I can get around to testing this out today or tomorrow.

**Comment by Cjkjvfnby** [comment]
Still in progress.

**Pull request closed without merging**
